apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: fhir-access-patient
  namespace: datamesh
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/fhir/*"]
    when:
    - key: request.auth.claims[realm_access][roles]
      values: ["Patient"]