apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: capsule-install
spec:
  profile: default
  meshConfig:
        accessLogFile: /dev/stdout
        enableTracing: true
  components:
    egressGateways:
    - name: idea4rc-egressgateway
      enabled: true